name: aurora_search
description: A metasearch library used by Aurora.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null

dependencies:
  args: ^2.4.2
  html: ^0.15.4
  http: ^1.1.0
  xml: ^6.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

topics:
  - metasearch
  - duckduckgo
  - bing
  - web-scraping
  - cli
